### ISSUE TITLE
Illegal match results are not validated when generating new rounds. Two cases.

### ISSUE THREAD

**Issue by armoredgear7** [Killerardvark/Cryodex#1]
See image:
![cryodexbugsv3 8 2](https://cloud.githubusercontent.com/assets/9486041/6136552/8b30b9d6-b13f-11e4-8603-27e38e063063.png)

**Comment by Killerardvark** [comment]
Fixed. Combobox is now defaulted to disabled and the points determine the results. You can turn on the combo box using the view menu, but there is a check to make sure the points match the results.

**Comment by armoredgear7** [comment]
Elegant fix in 3.8.4, works nicely.
