### ISSUE TITLE
Source Code??

### ISSUE THREAD

**Issue by kingargyle** [Killerardvark/Cryodex#2]
Is this official, or an unoffical repository?  It would be nice to have source code so that the community can contribute to it.  Especially since Fantasy Flight is creating their own tournament software.

**Comment by Killerardvark** [comment]
I've been using this more for just distribution. I believe the source code
is in the jar unless I changed my export setting and forgot. Is there
something in particular you would like to contribute?

I'm up open to suggestions or even module style improvement, but for the
time being I'm trying to keep the project "mine" first to have control and
second to avoid confusion with where any donated funds go.

Don't take me for an anti open source programmer though. I am open to
discussion on the topic.

**Comment by kingargyle** [comment]
Source code isn't in the JAR file, only the byte code Class files.   There are multiple ways to keep source under your control the most strict being GPL so that people that do take it and fork it have to open source it in their product if they make changes to it.   The most liberal being MIT and BSD which is basicaly do anything you want licenses.     The more middle ground bing LGPL, Apache, and EPL licenses, which if you use Apache, you maintain copyright to everything.

Open sourcing the code does not necessarily mean that you lose control of the code, but you can still require people to submit pull requrests to you.   By making the code open, you can get more eyes on it to help you out with new features and functionality.  Plus if you ever do decide to not work on it any more, the community that uses the software isn't left high and dry with only Fantasy Flights software to fall back on to.

Personally I think that Cryodex could excel as an open source platform for the community as a whole to contribute too.   One thing that would be nice maybe from a players point of view is an app or something that we could import or builds to and give to the tournament organizer ahead of time.   I also do not know what formats you currently except for importing squadrons.   Personally I use x-wing build uk for maintaining squad lists, and I know they have an export format, does Crydoex support that or a way to batch import files?

All stuff that could be added by the community instead of just having open person maintaing things.

**Comment by Killerardvark** [comment]
I'm currently working on a drastic change that would allow Cryodex to be
much more modular. For instance if someone wanted to make it work with
another game system they could write their own module and it would be easy
to integrate. Writing the Imperial Assault version got me going on that.
Maybe once that drops I'll open it up a lot more to other people.

On a further note, if I ever decide to stop doing what I do I will
definitely be putting the source code online for anyone else to pick up and
go with.

I'm very interested to see what FFG comes up with for their software.
Perhaps Cryodex won't even be necessary at that point.

**Comment by Killerardvark** [comment]
Project CryodexSource is the new repository with the source included
