### ISSUE TITLE
elimination round (x-wing) DRAW

### ISSUE THREAD

**Issue by Mu0n** [Killerardvark/Cryodex#4]
we ran a local 12 people tournament today with 4 swiss and cut to top 4 (we had more time in this other venue) but one of the matches of the top 4 was a draw, 0-0. A winner was still determined due to the tournament FAQ covering this case - player with initiative still wins. 
 
However, when I try to generate the next round, cryodex simply silently does nothing. It doesn't freeze as I can go into the menus fine, but it just won't do the top 2 panel.

**Comment by Killerardvark** [comment]
Moved to CryodexSource issue section.
